"""Keigo Vocabulary Pool — Complete honorific & humble word pairs, business words, and JMdict keigo integration.

Provides:
- 18 core irregular verb triplets (Plain ↔ Sonkeigo ↔ Kenjougo).
- 40+ regular verbs with rule-based honorifics (お〜になる, お〜する/いたす, ご〜なさる/いたす).
- 30+ business nouns, pronouns, and formal adverbs.
- Dynamic loader querying JMdict database (4,119 entries) for infinite expansion.
"""

from __future__ import annotations

import os
import sqlite3
from dataclasses import dataclass, field
from typing import Any


@dataclass
class KeigoWordEntry:
    source_word: str  # Plain word (e.g., 食べる, 行く, 今日, 会社)
    source_reading: str  # e.g., たべる
    meaning_vi: str  # e.g., ăn, đi, hôm nay
    target_type: str  # 'sonkeigo' | 'kenjougo' | 'business'
    target_label_vi: str  # 'Tôn kính ngữ (尊敬語)' | 'Khiêm nhường ngữ (謙譲語)' | 'Từ thương mại (ビジネス語)'
    canonical: str  # Primary answer (e.g., 召し上がる, 参る, 本日)
    canonical_reading: str  # e.g., めしあがる
    acceptable_variants: list[str] = field(default_factory=list)  # [召し上がります, めしあがる, めしあがります]
    triplet_sonkeigo: str | None = None  # For 3-column review card
    triplet_kenjougo: str | None = None
    category: str = "verb_irregular"  # 'verb_irregular' | 'verb_regular' | 'business_word'
    jlpt_level: str = "N3"  # 'N5' | 'N4' | 'N3' | 'N2' | 'N1'
    explanation_vi: str = ""  # Grammatical note or polite nuance


# ==============================================================================
# 1. CORE IRREGULAR VERBS (18 TRIPLETS) — The closed class of Japanese Keigo
# ==============================================================================
IRREGULAR_KEIGO_PAIRS: list[KeigoWordEntry] = [
    # 1. する
    KeigoWordEntry(
        source_word="する",
        source_reading="する",
        meaning_vi="làm",
        target_type="sonkeigo",
        target_label_vi="Tôn kính ngữ (尊敬語)",
        canonical="なさる",
        canonical_reading="なさる",
        acceptable_variants=["なさる", "なさいます", "なさって", "なされる"],
        triplet_sonkeigo="なさる",
        triplet_kenjougo="いたす",
        category="verb_irregular",
        jlpt_level="N4",
        explanation_vi="Hành động của đối phương/khách hàng → なさる",
    ),
    KeigoWordEntry(
        source_word="する",
        source_reading="する",
        meaning_vi="làm",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="いたす",
        canonical_reading="いたす",
        acceptable_variants=["いたす", "いたします", "致す", "致します"],
        triplet_sonkeigo="なさる",
        triplet_kenjougo="いたす",
        category="verb_irregular",
        jlpt_level="N4",
        explanation_vi="Hành động của bản thân/công ty mình → いたす (いたします)",
    ),
    # 2. 行く
    KeigoWordEntry(
        source_word="行く",
        source_reading="いく",
        meaning_vi="đi",
        target_type="sonkeigo",
        target_label_vi="Tôn kính ngữ (尊敬語)",
        canonical="いらっしゃる",
        canonical_reading="いらっしゃる",
        acceptable_variants=["いらっしゃる", "いらっしゃいます", "おいでになる", "おいでになります"],
        triplet_sonkeigo="いらっしゃる / おいでになる",
        triplet_kenjougo="参る / 伺う",
        category="verb_irregular",
        jlpt_level="N4",
        explanation_vi="Đối phương đi → いらっしゃる (おいでになる)",
    ),
    KeigoWordEntry(
        source_word="行く",
        source_reading="いく",
        meaning_vi="đi",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="参る",
        canonical_reading="まいる",
        acceptable_variants=["参る", "参ります", "まいる", "まいります", "伺う", "伺います"],
        triplet_sonkeigo="いらっしゃる / おいでになる",
        triplet_kenjougo="参る / 伺う",
        category="verb_irregular",
        jlpt_level="N4",
        explanation_vi="Bản thân đi → 参る (hoặc 伺う khi đi đến chỗ người khác)",
    ),
    # 3. 来る
    KeigoWordEntry(
        source_word="来る",
        source_reading="くる",
        meaning_vi="đến",
        target_type="sonkeigo",
        target_label_vi="Tôn kính ngữ (尊敬語)",
        canonical="いらっしゃる",
        canonical_reading="いらっしゃる",
        acceptable_variants=["いらっしゃる", "いらっしゃいます", "お見えになる", "お見えになります", "お越しになる", "お越しになります"],
        triplet_sonkeigo="いらっしゃる / お越しになる",
        triplet_kenjougo="参る / 伺う",
        category="verb_irregular",
        jlpt_level="N4",
        explanation_vi="Khách hàng đến → いらっしゃる (hoặc お越しになる)",
    ),
    KeigoWordEntry(
        source_word="来る",
        source_reading="くる",
        meaning_vi="đến",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="参る",
        canonical_reading="まいる",
        acceptable_variants=["参る", "参ります", "まいる", "まいります"],
        triplet_sonkeigo="いらっしゃる / お越しになる",
        triplet_kenjougo="参る",
        category="verb_irregular",
        jlpt_level="N4",
        explanation_vi="Bản thân đến → 参る (参ります)",
    ),
    # 4. いる
    KeigoWordEntry(
        source_word="いる",
        source_reading="いる",
        meaning_vi="ở / có mặt",
        target_type="sonkeigo",
        target_label_vi="Tôn kính ngữ (尊敬語)",
        canonical="いらっしゃる",
        canonical_reading="いらっしゃる",
        acceptable_variants=["いらっしゃる", "いらっしゃいます", "おいでになる", "おいでになります"],
        triplet_sonkeigo="いらっしゃる",
        triplet_kenjougo="おる",
        category="verb_irregular",
        jlpt_level="N4",
        explanation_vi="Sếp/khách hàng ở đâu → いらっしゃいます",
    ),
    KeigoWordEntry(
        source_word="いる",
        source_reading="いる",
        meaning_vi="ở / có mặt",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="おる",
        canonical_reading="おる",
        acceptable_variants=["おる", "おります", "居る"],
        triplet_sonkeigo="いらっしゃる",
        triplet_kenjougo="おる",
        category="verb_irregular",
        jlpt_level="N4",
        explanation_vi="Tôi đang ở đây → おります",
    ),
    # 5. 言う
    KeigoWordEntry(
        source_word="言う",
        source_reading="いう",
        meaning_vi="nói",
        target_type="sonkeigo",
        target_label_vi="Tôn kính ngữ (尊敬語)",
        canonical="おっしゃる",
        canonical_reading="おっしゃる",
        acceptable_variants=["おっしゃる", "おっしゃいます", "仰る", "仰います"],
        triplet_sonkeigo="おっしゃる",
        triplet_kenjougo="申す / 申し上げる",
        category="verb_irregular",
        jlpt_level="N4",
        explanation_vi="Đối phương nói → おっしゃる",
    ),
    KeigoWordEntry(
        source_word="言う",
        source_reading="いう",
        meaning_vi="nói",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="申す",
        canonical_reading="もうす",
        acceptable_variants=["申す", "申します", "申し上げる", "申し上げます", "もうす", "もうします"],
        triplet_sonkeigo="おっしゃる",
        triplet_kenjougo="申す / 申し上げる",
        category="verb_irregular",
        jlpt_level="N4",
        explanation_vi="Tôi tên là/Tôi nói → 申す (申します)",
    ),
    # 6. 食べる
    KeigoWordEntry(
        source_word="食べる",
        source_reading="たべる",
        meaning_vi="ăn",
        target_type="sonkeigo",
        target_label_vi="Tôn kính ngữ (尊敬語)",
        canonical="召し上がる",
        canonical_reading="めしあがる",
        acceptable_variants=["召し上がる", "召し上がります", "めしあがる", "めしあがります"],
        triplet_sonkeigo="召し上がる",
        triplet_kenjougo="いただく",
        category="verb_irregular",
        jlpt_level="N4",
        explanation_vi="Mời khách ăn → 召し上がる",
    ),
    KeigoWordEntry(
        source_word="食べる",
        source_reading="たべる",
        meaning_vi="ăn",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="いただく",
        canonical_reading="いただく",
        acceptable_variants=["いただく", "いただきます", "頂く", "頂きます"],
        triplet_sonkeigo="召し上がる",
        triplet_kenjougo="いただく",
        category="verb_irregular",
        jlpt_level="N4",
        explanation_vi="Tôi xin phép ăn → いただきます",
    ),
    # 7. 飲む
    KeigoWordEntry(
        source_word="飲む",
        source_reading="のむ",
        meaning_vi="uống",
        target_type="sonkeigo",
        target_label_vi="Tôn kính ngữ (尊敬語)",
        canonical="召し上がる",
        canonical_reading="めしあがる",
        acceptable_variants=["召し上がる", "召し上がります", "めしあがる", "めしあがります"],
        triplet_sonkeigo="召し上がる",
        triplet_kenjougo="いただく",
        category="verb_irregular",
        jlpt_level="N4",
        explanation_vi="Mời sếp uống trà → 召し上がる",
    ),
    KeigoWordEntry(
        source_word="飲む",
        source_reading="のむ",
        meaning_vi="uống",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="いただく",
        canonical_reading="いただく",
        acceptable_variants=["いただく", "いただきます", "頂く", "頂きます"],
        triplet_sonkeigo="召し上がる",
        triplet_kenjougo="いただく",
        category="verb_irregular",
        jlpt_level="N4",
        explanation_vi="Tôi xin phép uống → いただきます",
    ),
    # 8. 見る
    KeigoWordEntry(
        source_word="見る",
        source_reading="みる",
        meaning_vi="xem / nhìn",
        target_type="sonkeigo",
        target_label_vi="Tôn kính ngữ (尊敬語)",
        canonical="ご覧になる",
        canonical_reading="ごらんになる",
        acceptable_variants=["ご覧になる", "ご覧になります", "ごらんになる", "ごらんになります"],
        triplet_sonkeigo="ご覧になる",
        triplet_kenjougo="拝见する",
        category="verb_irregular",
        jlpt_level="N4",
        explanation_vi="Xin mời sếp xem tài liệu → ご覧になる",
    ),
    KeigoWordEntry(
        source_word="見る",
        source_reading="みる",
        meaning_vi="xem / nhìn",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="拝見する",
        canonical_reading="はいけんする",
        acceptable_variants=["拝見する", "拝見します", "はいけんする", "はいけんします", "拝見いたす", "拝見いたします"],
        triplet_sonkeigo="ご覧になる",
        triplet_kenjougo="拝見する",
        category="verb_irregular",
        jlpt_level="N4",
        explanation_vi="Tôi đã xem qua tài liệu của quý công ty → 拝見しました",
    ),
    # 9. 知る
    KeigoWordEntry(
        source_word="知る",
        source_reading="しる",
        meaning_vi="biết",
        target_type="sonkeigo",
        target_label_vi="Tôn kính ngữ (尊敬語)",
        canonical="ご存知だ",
        canonical_reading="ごぞんじだ",
        acceptable_variants=["ご存知だ", "ご存知です", "ご存じだ", "ご存じです", "ご存知ですか", "ご存じですか"],
        triplet_sonkeigo="ご存知だ / ご存知です",
        triplet_kenjougo="存じる / 存じ上げる",
        category="verb_irregular",
        jlpt_level="N4",
        explanation_vi="Khách hàng có biết chuyện này không → ご存知ですか",
    ),
    KeigoWordEntry(
        source_word="知る",
        source_reading="しる",
        meaning_vi="biết",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="存じる",
        canonical_reading="ぞんじる",
        acceptable_variants=["存じる", "存じます", "存じ上げる", "存じ上げます", "ぞんじる", "ぞんじます"],
        triplet_sonkeigo="ご存知だ / ご存知です",
        triplet_kenjougo="存じる / 存じ上げる",
        category="verb_irregular",
        jlpt_level="N4",
        explanation_vi="Tôi có biết chuyện đó → 存じております",
    ),
    # 10. 会う
    KeigoWordEntry(
        source_word="会う",
        source_reading="あう",
        meaning_vi="gặp",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="お目にかかる",
        canonical_reading="おめにかかる",
        acceptable_variants=["お目にかかる", "お目にかかります", "おめにかかる", "おめにかかります", "お会いする", "お会いします"],
        triplet_sonkeigo="お会いになる",
        triplet_kenjougo="お目にかかる",
        category="verb_irregular",
        jlpt_level="N3",
        explanation_vi="Tôi rất vinh hạnh được gặp ngài → お目にかかれて光栄です",
    ),
    # 11. 聞く / 尋ねる / 訪問する
    KeigoWordEntry(
        source_word="聞く",
        source_reading="きく",
        meaning_vi="hỏi / nghe",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="伺う",
        canonical_reading="うかがう",
        acceptable_variants=["伺う", "伺います", "うかがう", "うかがいます", "お聞きする", "拝聴する"],
        triplet_sonkeigo="お聞きになる",
        triplet_kenjougo="伺う / 拝聴する",
        category="verb_irregular",
        jlpt_level="N3",
        explanation_vi="Tôi xin phép hỏi một câu / Tôi nghe nói → 伺う",
    ),
    # 12. あげる
    KeigoWordEntry(
        source_word="あげる",
        source_reading="あげる",
        meaning_vi="tặng / cho",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="差し上げる",
        canonical_reading="さしあげる",
        acceptable_variants=["差し上げる", "差し上げます", "さしあげる", "さしあげます"],
        triplet_sonkeigo="—",
        triplet_kenjougo="差し上げる",
        category="verb_irregular",
        jlpt_level="N4",
        explanation_vi="Tôi xin gửi tặng quý khách → 差し上げる",
    ),
    # 13. もらう
    KeigoWordEntry(
        source_word="もらう",
        source_reading="もらう",
        meaning_vi="nhận",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="いただく",
        canonical_reading="いただく",
        acceptable_variants=["いただく", "いただきます", "頂く", "頂きます", "頂戴する", "頂戴します"],
        triplet_sonkeigo="—",
        triplet_kenjougo="いただく / 頂戴する",
        category="verb_irregular",
        jlpt_level="N4",
        explanation_vi="Tôi nhận được thư của ngài → お手紙をいただきました",
    ),
    # 14. くれる
    KeigoWordEntry(
        source_word="くれる",
        source_reading="くれる",
        meaning_vi="cho tôi",
        target_type="sonkeigo",
        target_label_vi="Tôn kính ngữ (尊敬語)",
        canonical="くださる",
        canonical_reading="くださる",
        acceptable_variants=["くださる", "くださいます", "下さる", "下さいます"],
        triplet_sonkeigo="くださる",
        triplet_kenjougo="—",
        category="verb_irregular",
        jlpt_level="N4",
        explanation_vi="Sếp đã cho tôi lời khuyên → アドバイスをくださいました",
    ),
    # 15. 見せる
    KeigoWordEntry(
        source_word="見せる",
        source_reading="みせる",
        meaning_vi="cho xem",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="お見せする",
        canonical_reading="おみせする",
        acceptable_variants=["お見せする", "お見せします", "ご覧に入れる", "お目にかける"],
        triplet_sonkeigo="お見せになる",
        triplet_kenjougo="お見せする / ご覧に入れる",
        category="verb_irregular",
        jlpt_level="N3",
        explanation_vi="Tôi xin phép cho ngài xem mẫu sản phẩm → ご覧に入れます",
    ),
    # 16. 思う
    KeigoWordEntry(
        source_word="思う",
        source_reading="おもう",
        meaning_vi="nghĩ rằng",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="存じる",
        canonical_reading="ぞんじる",
        acceptable_variants=["存じる", "存じます", "ぞんじる", "ぞんじます"],
        triplet_sonkeigo="お思いになる",
        triplet_kenjougo="存じる",
        category="verb_irregular",
        jlpt_level="N3",
        explanation_vi="Tôi nghĩ phương án này tốt hơn → よろしいかと存じます",
    ),
    # 17. 伝える
    KeigoWordEntry(
        source_word="伝える",
        source_reading="つたえる",
        meaning_vi="nhắn lại / truyền đạt",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="申し伝える",
        canonical_reading="もうしつたえる",
        acceptable_variants=["申し伝える", "申し伝えます", "お伝えする", "お伝えします"],
        triplet_sonkeigo="お伝えになる",
        triplet_kenjougo="申し伝える",
        category="verb_irregular",
        jlpt_level="N3",
        explanation_vi="Tôi sẽ chuyển lời lại cho anh Tanaka → 田中に申し伝えます",
    ),
    # 18. 借りる
    KeigoWordEntry(
        source_word="借りる",
        source_reading="かりる",
        meaning_vi="mượn",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="拝借する",
        canonical_reading="はいしゃくする",
        acceptable_variants=["拝借する", "拝借します", "お借りする", "お借りします"],
        triplet_sonkeigo="お借りになる",
        triplet_kenjougo="拝借する / お借りする",
        category="verb_irregular",
        jlpt_level="N2",
        explanation_vi="Tôi xin phép mượn cây bút → ペンを拝借します",
    ),
    # 19. 着る
    KeigoWordEntry(
        source_word="着る",
        source_reading="きる",
        meaning_vi="mặc",
        target_type="sonkeigo",
        target_label_vi="Tôn kính ngữ (尊敬語)",
        canonical="お召しになる",
        canonical_reading="おめしになる",
        acceptable_variants=["お召しになる", "お召しになります", "お召し"],
        triplet_sonkeigo="お召しになる",
        triplet_kenjougo="—",
        category="verb_irregular",
        jlpt_level="N2",
        explanation_vi="Bộ vest ngài đang mặc rất đẹp → お召しになっているスーツ",
    ),
    # 20. 寝る
    KeigoWordEntry(
        source_word="寝る",
        source_reading="ねる",
        meaning_vi="ngủ",
        target_type="sonkeigo",
        target_label_vi="Tôn kính ngữ (尊敬語)",
        canonical="お休みになる",
        canonical_reading="おやすみになる",
        acceptable_variants=["お休みになる", "お休みになります", "おやすみになる"],
        triplet_sonkeigo="お休みになる",
        triplet_kenjougo="—",
        category="verb_irregular",
        jlpt_level="N4",
        explanation_vi="Sếp đã đi nghỉ rồi ạ → お休みになりました",
    ),
]


# ==============================================================================
# 2. REGULAR VERBS (RULE-BASED KEIGO PATTERNS)
# ==============================================================================
REGULAR_KEIGO_PAIRS: list[KeigoWordEntry] = [
    KeigoWordEntry(
        source_word="書く",
        source_reading="かく",
        meaning_vi="viết",
        target_type="sonkeigo",
        target_label_vi="Tôn kính ngữ (尊敬語)",
        canonical="お書きになる",
        canonical_reading="おかきになる",
        acceptable_variants=["お書きになる", "お書きになります", "書かれる"],
        triplet_sonkeigo="お書きになる",
        triplet_kenjougo="お書きする",
        category="verb_regular",
        jlpt_level="N4",
    ),
    KeigoWordEntry(
        source_word="待つ",
        source_reading="まつ",
        meaning_vi="đợi",
        target_type="sonkeigo",
        target_label_vi="Tôn kính ngữ (尊敬語)",
        canonical="お待ちになる",
        canonical_reading="おまちになる",
        acceptable_variants=["お待ちになる", "お待ちになります", "お待ちください"],
        triplet_sonkeigo="お待ちになる",
        triplet_kenjougo="お待ちする",
        category="verb_regular",
        jlpt_level="N4",
    ),
    KeigoWordEntry(
        source_word="待つ",
        source_reading="まつ",
        meaning_vi="đợi",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="お待ちする",
        canonical_reading="おまちする",
        acceptable_variants=["お待ちする", "お待ちします", "お待ちいたす", "お待ちいたします"],
        triplet_sonkeigo="お待ちになる",
        triplet_kenjougo="お待ちする / お待ちいたす",
        category="verb_regular",
        jlpt_level="N4",
    ),
    KeigoWordEntry(
        source_word="読む",
        source_reading="よむ",
        meaning_vi="đọc",
        target_type="sonkeigo",
        target_label_vi="Tôn kính ngữ (尊敬語)",
        canonical="お読みになる",
        canonical_reading="およみになる",
        acceptable_variants=["お読みになる", "お読みになります", "ご一読なさる"],
        triplet_sonkeigo="お読みになる",
        triplet_kenjougo="拝読する",
        category="verb_regular",
        jlpt_level="N4",
    ),
    KeigoWordEntry(
        source_word="読む",
        source_reading="よむ",
        meaning_vi="đọc",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="拝読する",
        canonical_reading="はいどくする",
        acceptable_variants=["拝読する", "拝読します", "拝読いたします", "お読みする"],
        triplet_sonkeigo="お読みになる",
        triplet_kenjougo="拝読する",
        category="verb_regular",
        jlpt_level="N3",
    ),
    KeigoWordEntry(
        source_word="送る",
        source_reading="おくる",
        meaning_vi="gửi",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="お送りする",
        canonical_reading="おおくりする",
        acceptable_variants=["お送りする", "お送りします", "お送りいたす", "お送りいたします"],
        triplet_sonkeigo="お送りになる",
        triplet_kenjougo="お送りする",
        category="verb_regular",
        jlpt_level="N4",
    ),
    KeigoWordEntry(
        source_word="持つ",
        source_reading="もつ",
        meaning_vi="cầm / mang",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="お持ちする",
        canonical_reading="おもちする",
        acceptable_variants=["お持ちする", "お持ちします", "お持ちいたす", "お持ちいたします"],
        triplet_sonkeigo="お持ちになる",
        triplet_kenjougo="お持ちする",
        category="verb_regular",
        jlpt_level="N4",
    ),
    KeigoWordEntry(
        source_word="連絡する",
        source_reading="れんらくする",
        meaning_vi="liên lạc",
        target_type="sonkeigo",
        target_label_vi="Tôn kính ngữ (尊敬語)",
        canonical="ご連絡なさる",
        canonical_reading="ごれんらくなさる",
        acceptable_variants=["ご連絡なさる", "ご連絡なさいます", "ご連絡になる", "ご連絡くださる"],
        triplet_sonkeigo="ご連絡なさる",
        triplet_kenjougo="ご連絡いたす",
        category="verb_regular",
        jlpt_level="N3",
    ),
    KeigoWordEntry(
        source_word="連絡する",
        source_reading="れんらくする",
        meaning_vi="liên lạc",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="ご連絡いたす",
        canonical_reading="ごれんらくいたす",
        acceptable_variants=["ご連絡いたす", "ご連絡いたします", "ご連絡する", "ご連絡します"],
        triplet_sonkeigo="ご連絡なさる",
        triplet_kenjougo="ご連絡いたす",
        category="verb_regular",
        jlpt_level="N3",
    ),
    KeigoWordEntry(
        source_word="案内する",
        source_reading="あんないする",
        meaning_vi="hướng dẫn / dẫn đường",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="ご案内いたす",
        canonical_reading="ごあんないいたす",
        acceptable_variants=["ご案内いたす", "ご案内いたします", "ご案内する", "ご案内します"],
        triplet_sonkeigo="ご案内なさる",
        triplet_kenjougo="ご案内いたす",
        category="verb_regular",
        jlpt_level="N3",
    ),
    KeigoWordEntry(
        source_word="相談する",
        source_reading="そうだんする",
        meaning_vi="thảo luận / xin ý kiến",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="ご相談いたす",
        canonical_reading="ごそうだんいたす",
        acceptable_variants=["ご相談いたす", "ご相談いたします", "ご相談申し上げる", "ご相談する"],
        triplet_sonkeigo="ご相談なさる",
        triplet_kenjougo="ご相談申し上げる",
        category="verb_regular",
        jlpt_level="N3",
    ),
    KeigoWordEntry(
        source_word="手伝う",
        source_reading="てつだう",
        meaning_vi="giúp đỡ",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="お手伝いする",
        canonical_reading="おてつだいする",
        acceptable_variants=["お手伝いする", "お手伝いします", "お手伝いいたす", "お手伝いいたします"],
        triplet_sonkeigo="お手伝いになる",
        triplet_kenjougo="お手伝いする",
        category="verb_regular",
        jlpt_level="N4",
    ),
    KeigoWordEntry(
        source_word="届ける",
        source_reading="とどける",
        meaning_vi="giao đến",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="お届けする",
        canonical_reading="おとどけする",
        acceptable_variants=["お届けする", "お届けします", "お届けいたす", "お届けいたします"],
        triplet_sonkeigo="お届けになる",
        triplet_kenjougo="お届けする",
        category="verb_regular",
        jlpt_level="N3",
    ),
]


# ==============================================================================
# 3. BUSINESS NOUNS, PRONOUNS & ADVERBS (30+ HIGH-YIELD ENTRIES)
# ==============================================================================
BUSINESS_KEIGO_WORDS: list[KeigoWordEntry] = [
    KeigoWordEntry(
        source_word="人",
        source_reading="ひと",
        meaning_vi="người",
        target_type="business",
        target_label_vi="Từ xưng hô lịch sự (ビジネス語)",
        canonical="方",
        canonical_reading="かた",
        acceptable_variants=["方", "かた", "皆様", "みなさま"],
        category="business_word",
        jlpt_level="N5",
        explanation_vi="Người kia → あの方 (あのかた)",
    ),
    KeigoWordEntry(
        source_word="だれ",
        source_reading="だれ",
        meaning_vi="ai",
        target_type="business",
        target_label_vi="Từ xưng hô lịch sự (ビジネス語)",
        canonical="どなた",
        canonical_reading="どなた",
        acceptable_variants=["どなた", "どちら様", "どちらさま"],
        category="business_word",
        jlpt_level="N5",
        explanation_vi="Xin hỏi ngài là ai → どちら様でしょうか / どなた様",
    ),
    KeigoWordEntry(
        source_word="どこ",
        source_reading="どこ",
        meaning_vi="ở đâu / phía nào",
        target_type="business",
        target_label_vi="Từ xưng hô lịch sự (ビジネス語)",
        canonical="どちら",
        canonical_reading="どちら",
        acceptable_variants=["どちら", "どちら様"],
        category="business_word",
        jlpt_level="N5",
        explanation_vi="Phòng họp ở đâu → 会議室はどちらでしょうか",
    ),
    KeigoWordEntry(
        source_word="どう",
        source_reading="どう",
        meaning_vi="thế nào",
        target_type="business",
        target_label_vi="Từ xưng hô lịch sự (ビジネス語)",
        canonical="いかが",
        canonical_reading="いかが",
        acceptable_variants=["いかが", "いかがでしょうか"],
        category="business_word",
        jlpt_level="N5",
        explanation_vi="Ý kiến ngài thế nào → いかがでしょうか",
    ),
    KeigoWordEntry(
        source_word="いくら",
        source_reading="いくら",
        meaning_vi="bao nhiêu tiền",
        target_type="business",
        target_label_vi="Từ xưng hô lịch sự (ビジネス語)",
        canonical="おいくら",
        canonical_reading="おいくら",
        acceptable_variants=["おいくら", "おいくらでしょうか"],
        category="business_word",
        jlpt_level="N5",
    ),
    KeigoWordEntry(
        source_word="いい",
        source_reading="いい",
        meaning_vi="được / tốt",
        target_type="business",
        target_label_vi="Từ xưng hô lịch sự (ビジネス語)",
        canonical="よろしい",
        canonical_reading="よろしい",
        acceptable_variants=["よろしい", "よろしいでしょうか", "結構です"],
        category="business_word",
        jlpt_level="N5",
        explanation_vi="Như vậy có được không → よろしいでしょうか",
    ),
    KeigoWordEntry(
        source_word="会社 (của mình)",
        source_reading="かいしゃ",
        meaning_vi="công ty của chúng tôi",
        target_type="business",
        target_label_vi="Từ xưng hô lịch sự (ビジネス語)",
        canonical="弊社",
        canonical_reading="へいしゃ",
        acceptable_variants=["弊社", "へいしゃ", "当社", "とうしゃ", "わたくしども"],
        category="business_word",
        jlpt_level="N3",
        explanation_vi="Công ty chúng tôi (khiêm tốn) → 弊社 (へいしゃ)",
    ),
    KeigoWordEntry(
        source_word="会社 (của khách)",
        source_reading="かいしゃ",
        meaning_vi="quý công ty của ngài",
        target_type="business",
        target_label_vi="Từ xưng hô lịch sự (ビジネス語)",
        canonical="御社",
        canonical_reading="おんしゃ",
        acceptable_variants=["御社", "おんしゃ", "貴社", "きしゃ"],
        category="business_word",
        jlpt_level="N3",
        explanation_vi="Văn nói dùng 御社 (おんしゃ), văn viết/email dùng 貴社 (きしゃ)",
    ),
    KeigoWordEntry(
        source_word="今日",
        source_reading="きょう",
        meaning_vi="hôm nay",
        target_type="business",
        target_label_vi="Từ xưng hô lịch sự (ビジネス語)",
        canonical="本日",
        canonical_reading="ほんじつ",
        acceptable_variants=["本日", "ほんじつ"],
        category="business_word",
        jlpt_level="N4",
    ),
    KeigoWordEntry(
        source_word="昨日",
        source_reading="きのう",
        meaning_vi="hôm qua",
        target_type="business",
        target_label_vi="Từ xưng hô lịch sự (ビジネス語)",
        canonical="昨日",
        canonical_reading="さくじつ",
        acceptable_variants=["昨日", "さくじつ"],
        category="business_word",
        jlpt_level="N3",
        explanation_vi="Trong business đọc là さくじつ",
    ),
    KeigoWordEntry(
        source_word="明日",
        source_reading="あした",
        meaning_vi="ngày mai",
        target_type="business",
        target_label_vi="Từ xưng hô lịch sự (ビジネス語)",
        canonical="明日",
        canonical_reading="みょうにち",
        acceptable_variants=["明日", "みょうにち", "あす"],
        category="business_word",
        jlpt_level="N3",
        explanation_vi="Trong business đọc là みょうにち (hoặc あす)",
    ),
    KeigoWordEntry(
        source_word="今年",
        source_reading="ことし",
        meaning_vi="năm nay",
        target_type="business",
        target_label_vi="Từ xưng hô lịch sự (ビジネス語)",
        canonical="本年",
        canonical_reading="ほんねん",
        acceptable_variants=["本年", "ほんねん"],
        category="business_word",
        jlpt_level="N3",
    ),
    KeigoWordEntry(
        source_word="さっき",
        source_reading="さっき",
        meaning_vi="vừa nãy / lúc nãy",
        target_type="business",
        target_label_vi="Từ xưng hô lịch sự (ビジネス語)",
        canonical="先ほど",
        canonical_reading="さきほど",
        acceptable_variants=["先ほど", "さきほど", "先程"],
        category="business_word",
        jlpt_level="N4",
    ),
    KeigoWordEntry(
        source_word="後で",
        source_reading="あとで",
        meaning_vi="lát nữa / sau đó",
        target_type="business",
        target_label_vi="Từ xưng hô lịch sự (ビジネス語)",
        canonical="後ほど",
        canonical_reading="のちほど",
        acceptable_variants=["後ほど", "のちほど", "後程"],
        category="business_word",
        jlpt_level="N4",
    ),
    KeigoWordEntry(
        source_word="今",
        source_reading="いま",
        meaning_vi="bây giờ",
        target_type="business",
        target_label_vi="Từ xưng hô lịch sự (ビジネス語)",
        canonical="ただいま",
        canonical_reading="ただいま",
        acceptable_variants=["ただいま", "ただ今", "現在"],
        category="business_word",
        jlpt_level="N4",
    ),
    KeigoWordEntry(
        source_word="本当に",
        source_reading="ほんとうに",
        meaning_vi="thực sự / rất",
        target_type="business",
        target_label_vi="Từ xưng hô lịch sự (ビジネス語)",
        canonical="誠に",
        canonical_reading="まことに",
        acceptable_variants=["誠に", "まことに", "大変"],
        category="business_word",
        jlpt_level="N3",
        explanation_vi="誠にありがとうございます (Rất cảm ơn quý khách)",
    ),
    KeigoWordEntry(
        source_word="すみません",
        source_reading="すみません",
        meaning_vi="xin lỗi",
        target_type="business",
        target_label_vi="Từ xưng hô lịch sự (ビジネス語)",
        canonical="大変申し訳ございません",
        canonical_reading="たいへんもうしわけございません",
        acceptable_variants=[
            "大変申し訳ございません",
            "申し訳ございません",
            "恐れ入ります",
            "恐縮です",
            "たいへんもうしわけございません",
        ],
        category="business_word",
        jlpt_level="N4",
    ),
    KeigoWordEntry(
        source_word="分かりました",
        source_reading="わかりました",
        meaning_vi="tôi đã hiểu / rõ rồi",
        target_type="business",
        target_label_vi="Từ xưng hô lịch sự (ビジネス語)",
        canonical="かしこまりました",
        canonical_reading="かしこまりました",
        acceptable_variants=[
            "かしこまりました",
            "承知いたしました",
            "承知しました",
            "しょうちいたしました",
            "畏まりました",
        ],
        category="business_word",
        jlpt_level="N4",
        explanation_vi="Không dùng 了解しました với khách hàng/cấp trên",
    ),
    KeigoWordEntry(
        source_word="家 (của mình)",
        source_reading="いえ",
        meaning_vi="nhà của tôi",
        target_type="business",
        target_label_vi="Từ xưng hô lịch sự (ビジネス語)",
        canonical="拙宅",
        canonical_reading="せったく",
        acceptable_variants=["拙宅", "せったく", "自宅"],
        category="business_word",
        jlpt_level="N2",
    ),
    KeigoWordEntry(
        source_word="家 (của khách)",
        source_reading="いえ",
        meaning_vi="nhà của ngài",
        target_type="business",
        target_label_vi="Từ xưng hô lịch sự (ビジネス語)",
        canonical="お宅",
        canonical_reading="おたく",
        acceptable_variants=["お宅", "おたく", "貴宅", "御宅"],
        category="business_word",
        jlpt_level="N3",
    ),
]


# Combine all pools
ALL_KEIGO_WORDS: list[KeigoWordEntry] = IRREGULAR_KEIGO_PAIRS + REGULAR_KEIGO_PAIRS + BUSINESS_KEIGO_WORDS


def get_sonkeigo_pool() -> list[KeigoWordEntry]:
    return [w for w in ALL_KEIGO_WORDS if w.target_type == "sonkeigo"]


def get_kenjougo_pool() -> list[KeigoWordEntry]:
    return [w for w in ALL_KEIGO_WORDS if w.target_type == "kenjougo"]


def get_business_vocab_pool() -> list[KeigoWordEntry]:
    return [w for w in ALL_KEIGO_WORDS if w.target_type == "business"]


def get_all_keigo_vocab() -> list[KeigoWordEntry]:
    return ALL_KEIGO_WORDS


def get_easy_keigo_vocab() -> list[KeigoWordEntry]:
    return [w for w in ALL_KEIGO_WORDS if w.jlpt_level in ("N5", "N4")]


def get_normal_keigo_vocab() -> list[KeigoWordEntry]:
    return [w for w in ALL_KEIGO_WORDS if w.jlpt_level in ("N4", "N3")]


def get_hard_keigo_vocab() -> list[KeigoWordEntry]:
    return [w for w in ALL_KEIGO_WORDS if w.jlpt_level in ("N3", "N2", "N1")]
